//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paymentauthorization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string UserNAme { get; set; }
        public Nullable<int> Password { get; set; }
        public string Person_Name { get; set; }
        public Nullable<int> Person_phone { get; set; }
        public string Person_Address { get; set; }
    }
}
